apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservicemongo-deploy
  labels:
    name: orderservicemongo-deploy
    app: LMS
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orderservicemongo-pod
      app: LMS
  template:
    metadata:
      name: orderservicemongo-pod
      labels:
        name: orderservicemongo-pod
        app: LMS
    spec:
      containers:
        - name: orderservicemongo
          image: mongo
          ports:
            - containerPort: 27017
