apiVersion: v1
kind: Service
metadata:
  name: orderservicemongo
  labels:
    name: orderservicemongo-service
    app: LMS
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: orderservicemongo-pod
    app: LMS
