apiVersion: v1
kind: Service
metadata:
  name: userprofileservicemongo
  labels:
    name: userprofileservicemongo-service
    app: LMS
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: userprofileservicemongo-pod
    app: LMS
