apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientorderhandler-api-deploy
  labels:
    name: clientorderhandler-api-deploy
    app: LMS
spec:
  replicas: 2
  selector:
    matchLabels:
      name: clientorderhandler-api-pod
      app: LMS
  template:
    metadata:
      name: clientorderhandler-api-pod
      labels:
        name: clientorderhandler-api-pod
        app: LMS
    spec:
      containers:
        - name: clientorderhandler
          image: anandprakashdubey/clientorderhandler:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings_MongoDB
              value: "mongodb://orderhandlermongo:27017/OrderHandler"
            - name: PharmacyAPI
              value: http://pharmacyservice-api-service
            - name: OrderAPI
              value: http://orderservice-api-service
