apiVersion: v1
kind: Service
metadata:
  name: pharmacyservice-api-service
  labels:
    name: pharmacyservice-api-service
    app: LMS
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
  selector:
    name: pharmacyservice-api-pod
    app: LMS
